name: flutter_login
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.17
  charts_flutter: ^0.12.0
  cloud_firestore: ^5.4.4  # อัปเดตเวอร์ชัน
  firebase_core: 3.6.0     # อัปเดตเวอร์ชัน
  fl_chart: ^0.40.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
